# -*- coding: utf-8 -*-
"""Untitled22.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jLLcHJV5cJs2vRoxxMvI7H8_hSHpJdYw
"""

import pandas as pd
df=pd.DataFrame([[2,3,4,5],
                 [12,13,14,15]
                 22,23,24,25]],
                columns=['maths','english',]